# Generated by Django 3.2.12 on 2022-02-15 22:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(max_length=64, unique=True)),
                ('name_lower', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Investigator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namespace', models.SlugField(max_length=64)),
                ('name', models.SlugField(max_length=64)),
                ('authorization_domain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='anvil_tracker.group')),
            ],
        ),
        migrations.CreateModel(
            name='WorkspaceGroupAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_level', models.CharField(choices=[('OWNER', 'Owner'), ('WRITER', 'Writer'), ('READER', 'Reader')], default='READER', max_length=10)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anvil_tracker.group')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anvil_tracker.workspace')),
            ],
        ),
        migrations.CreateModel(
            name='GroupMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('MEMBER', 'Member'), ('ADMIN', 'Admin')], default='MEMBER', max_length=10)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anvil_tracker.group')),
                ('investigator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anvil_tracker.investigator')),
            ],
        ),
        migrations.AddConstraint(
            model_name='workspacegroupaccess',
            constraint=models.UniqueConstraint(fields=('group', 'workspace'), name='unique_workspace_group_access'),
        ),
        migrations.AddConstraint(
            model_name='workspace',
            constraint=models.UniqueConstraint(fields=('namespace', 'name'), name='unique_workspace'),
        ),
        migrations.AddConstraint(
            model_name='groupmembership',
            constraint=models.UniqueConstraint(fields=('investigator', 'group'), name='unique_group_membership'),
        ),
    ]
