# Generated by Django 3.2.12 on 2022-02-14 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Investigator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namespace', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=64)),
                ('authorization_domain', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='anvil_tracker.group')),
            ],
        ),
        migrations.CreateModel(
            name='WorkspaceGroupAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_level', models.CharField(choices=[('OWNER', 'Owner'), ('WRITER', 'Writer'), ('READER', 'Reader')], default='READER', max_length=10)),
                ('investigator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anvil_tracker.investigator')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anvil_tracker.workspace')),
            ],
        ),
        migrations.CreateModel(
            name='GroupMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('MEMBER', 'Member'), ('ADMIN', 'Admin')], default='MEMBER', max_length=10)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anvil_tracker.group')),
                ('investigator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anvil_tracker.investigator')),
            ],
        ),
    ]
