version: 2

sphinx:
  configuration: docs/conf.py

build:
  os: ubuntu-20.04
  tools:
    python: "3.9"
  jobs:
    build:
      html:
        - pip install hatch
        - mkdir -p $READTHEDOCS_OUTPUT/html/
        - export SPHINXBUILDDIR=../$READTHEDOCS_OUTPUT/
        - hatch run docs:build
