# Generated by Django 3.2.12 on 2022-02-16 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anvil_project_manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(max_length=64, unique=True)),
                ('name_lower', models.CharField(max_length=64, unique=True)),
            ],
        ),
    ]
