# Generated by Django 3.2.12 on 2022-04-05 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anvil_project_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupgroupmembership',
            name='child_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parent_memberships', to='anvil_project_manager.managedgroup'),
        ),
    ]
