# Generated by Django 3.2.12 on 2022-02-16 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anvil_project_manager', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Investigator',
            new_name='Researcher',
        ),
        migrations.RemoveConstraint(
            model_name='groupmembership',
            name='unique_group_membership',
        ),
        migrations.RenameField(
            model_name='groupmembership',
            old_name='investigator',
            new_name='researcher',
        ),
        migrations.AddConstraint(
            model_name='groupmembership',
            constraint=models.UniqueConstraint(fields=('researcher', 'group'), name='unique_group_membership'),
        ),
    ]
