# Generated by Django 3.2.12 on 2022-04-04 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anvil_project_manager', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GroupAccountMembership',
            new_name='ManagedGroupAccountMembership',
        ),
        migrations.RenameModel(
            old_name='GroupGroupMembership',
            new_name='ManagedGroupGroupMembership',
        ),
    ]
