# Generated by Django 3.2.12 on 2022-02-16 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anvil_project_manager', '0002_auto_20220216_1400'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workspacegroupaccess',
            old_name='access_level',
            new_name='access',
        ),
    ]
