# Generated by Django 3.2.12 on 2022-02-19 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anvil_project_manager', '0003_rename_access_level_workspacegroupaccess_access'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billingproject',
            name='name_lower',
        ),
        migrations.RemoveField(
            model_name='group',
            name='name_lower',
        ),
        migrations.RemoveField(
            model_name='workspace',
            name='authorization_domain',
        ),
    ]
