# Generated by Django 3.2.12 on 2022-02-23 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anvil_project_manager', '0004_auto_20220218_1655'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Researcher',
            new_name='Account',
        ),
        migrations.RemoveConstraint(
            model_name='groupmembership',
            name='unique_group_membership',
        ),
        migrations.RenameField(
            model_name='groupmembership',
            old_name='researcher',
            new_name='account',
        ),
        migrations.AddConstraint(
            model_name='groupmembership',
            constraint=models.UniqueConstraint(fields=('account', 'group'), name='unique_group_membership'),
        ),
    ]
