# Generated by Django 3.2.12 on 2022-02-23 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anvil_project_manager', '0005_auto_20220223_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_service_account',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
