# Generated by Django 3.2.12 on 2022-02-24 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anvil_project_manager', '0006_account_is_service_account'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GroupMembership',
            new_name='GroupAccountMembership',
        ),
        migrations.RemoveConstraint(
            model_name='groupaccountmembership',
            name='unique_group_membership',
        ),
        migrations.AddConstraint(
            model_name='groupaccountmembership',
            constraint=models.UniqueConstraint(fields=('account', 'group'), name='unique_group_account_membership'),
        ),
    ]
