# Generated by Django 3.2.12 on 2022-02-24 00:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anvil_project_manager', '0007_rename_group_membership_group_account_membership'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupGroupMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('MEMBER', 'Member'), ('ADMIN', 'Admin')], default='MEMBER', max_length=10)),
                ('child_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_groups', to='anvil_project_manager.group')),
                ('parent_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_groups', to='anvil_project_manager.group')),
            ],
        ),
        migrations.AddConstraint(
            model_name='groupgroupmembership',
            constraint=models.UniqueConstraint(fields=('parent_group', 'child_group'), name='unique_group_group_membership'),
        ),
    ]
