# Generated by Django 3.2.12 on 2022-03-01 22:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anvil_project_manager', '0008_groupgroupmembership'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupgroupmembership',
            name='child_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_memberships', to='anvil_project_manager.group'),
        ),
        migrations.AlterField(
            model_name='groupgroupmembership',
            name='parent_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_memberships', to='anvil_project_manager.group'),
        ),
    ]
