# Generated by Django 3.2.12 on 2022-03-11 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anvil_project_manager', '0009_auto_20220301_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='authorization_domains',
            field=models.ManyToManyField(to='anvil_project_manager.Group'),
        ),
    ]
