# Generated by Django 3.2.12 on 2022-03-10 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anvil_project_manager', '0009_auto_20220301_1433'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkspaceAuthorizationDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='anvil_project_manager.group')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authorization_domain', to='anvil_project_manager.workspace')),
            ],
        ),
        migrations.AddConstraint(
            model_name='workspaceauthorizationdomain',
            constraint=models.UniqueConstraint(fields=('workspace', 'group'), name='unique_workspace_authorization_domain'),
        ),
    ]
