# Generated by Django 3.2.12 on 2022-03-12 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anvil_project_manager', '0010_workspaceauthorizationdomain'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='is_managed_by_app',
            field=models.BooleanField(default=True),
        ),
    ]
