# Generated by Django 3.2.12 on 2022-03-17 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anvil_project_manager', '0012_case_insensitive_validators'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingproject',
            name='has_app_as_user',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
