# Generated by Django 3.2.12 on 2022-04-07 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anvil_consortium_manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnvilProjectManagerAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('anvil_project_manager_view', 'Anvil Project Manager View Permission'), ('anvil_project_manager_edit', 'Anvil Project Manager Edit Permission')],
                'managed': False,
                'default_permissions': (),
            },
        ),
    ]
