# Generated by Django 3.2.12 on 2022-10-28 14:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('anvil_consortium_manager', '0002_account_verification'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HistoricalWorkspaceGroupAccess',
            new_name='HistoricalWorkspaceGroupSharing',
        ),
        migrations.RenameModel(
            old_name='WorkspaceGroupAccess',
            new_name='WorkspaceGroupSharing',
        ),
        migrations.AlterModelOptions(
            name='historicalworkspacegroupsharing',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical workspace group sharing', 'verbose_name_plural': 'historical workspace group access'},
        ),
        migrations.RemoveConstraint(
            model_name='workspacegroupsharing',
            name='unique_workspace_group_access',
        ),
        migrations.AddConstraint(
            model_name='workspacegroupsharing',
            constraint=models.UniqueConstraint(fields=('group', 'workspace'), name='unique_workspace_group_sharing'),
        ),
    ]
