# Generated by Django 3.2.12 on 2022-11-02 15:21

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('anvil_consortium_manager', '0002_account_verification'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HistoricalWorkspaceGroupAccess',
            new_name='HistoricalWorkspaceGroupSharing',
        ),
        migrations.RenameModel(
            old_name='WorkspaceGroupAccess',
            new_name='WorkspaceGroupSharing',
        ),
        migrations.AlterModelOptions(
            name='historicalworkspacegroupsharing',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical workspace group sharing', 'verbose_name_plural': 'historical workspace group sharing'},
        ),
        migrations.AlterModelOptions(
            name='workspacegroupsharing',
            options={'verbose_name_plural': 'workspace group sharing'},
        ),
    ]
