# Generated by Django 3.2.12 on 2022-11-22 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anvil_consortium_manager', '0003_rename_workspacegroupaccess'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingproject',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='historicalbillingproject',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
