# Generated by Django 3.2.12 on 2022-05-02 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anvil_consortium_manager', '0003_anvilprojectmanageraccess'),
        ('anvil_consortium_manager', '0003_timestampedmodel'),
    ]

    operations = [
    ]
