# Generated by Django 3.2.12 on 2022-05-03 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anvil_consortium_manager', '0004_merge_20220502_1513'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anvilprojectmanageraccess',
            options={'default_permissions': (), 'managed': False, 'permissions': [('anvil_project_manager_edit', 'AnVIL Project Manager Edit Permission'), ('anvil_project_manager_view', 'AnVIL Project Manager View Permission')]},
        ),
    ]
