# Generated by Django 3.2.12 on 2022-11-22 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anvil_consortium_manager', '0004_auto_20221121_1603'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billingproject',
            old_name='description',
            new_name='note',
        ),
        migrations.RenameField(
            model_name='historicalbillingproject',
            old_name='description',
            new_name='note',
        ),
    ]
