# Generated by Django 3.2.12 on 2022-11-22 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anvil_consortium_manager', '0005_auto_20221121_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingproject',
            name='note',
            field=models.TextField(blank=True, help_text='Additional notes.'),
        ),
        migrations.AlterField(
            model_name='historicalbillingproject',
            name='note',
            field=models.TextField(blank=True, help_text='Additional notes.'),
        ),
    ]
