# Generated by Django 3.2.12 on 2023-01-23 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anvil_consortium_manager', '0006_historicaldefaultworkspacedata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalworkspacegroupsharing',
            name='access',
            field=models.CharField(choices=[('OWNER', 'Owner'), ('WRITER', 'Writer'), ('READER', 'Reader')], default='READER', help_text='Access level that this ManagedGroup has to this Workspace.\n            A "Reader" can see data in the workspace.\n            A "Writer" can add or remove data in the workspace.\n            An "Owner" can share the workspace with others or delete the workspace.', max_length=10),
        ),
        migrations.AlterField(
            model_name='workspacegroupsharing',
            name='access',
            field=models.CharField(choices=[('OWNER', 'Owner'), ('WRITER', 'Writer'), ('READER', 'Reader')], default='READER', help_text='Access level that this ManagedGroup has to this Workspace.\n            A "Reader" can see data in the workspace.\n            A "Writer" can add or remove data in the workspace.\n            An "Owner" can share the workspace with others or delete the workspace.', max_length=10),
        ),
    ]
