# Generated by Django 3.2.12 on 2022-11-22 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anvil_consortium_manager', '0006_auto_20221121_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='note',
            field=models.TextField(blank=True, help_text='Additional notes.'),
        ),
        migrations.AddField(
            model_name='historicalaccount',
            name='note',
            field=models.TextField(blank=True, help_text='Additional notes.'),
        ),
    ]
