# Generated by Django 3.2.12 on 2022-06-28 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anvil_consortium_manager', '0007_groupaccountmembership_account_historicforeignkey'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalworkspacegroupaccess',
            name='can_compute',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workspacegroupaccess',
            name='can_compute',
            field=models.BooleanField(default=False),
        ),
    ]
