# Generated by Django 3.2.12 on 2022-11-22 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anvil_consortium_manager', '0007_auto_20221121_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmanagedgroup',
            name='note',
            field=models.TextField(blank=True, help_text='Additional notes.'),
        ),
        migrations.AddField(
            model_name='managedgroup',
            name='note',
            field=models.TextField(blank=True, help_text='Additional notes.'),
        ),
    ]
