# Generated by Django 3.2.12 on 2023-04-10 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anvil_consortium_manager', '0008_workspace_is_locked'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anvilprojectmanageraccess',
            options={'default_permissions': (), 'managed': False, 'permissions': [('anvil_project_manager_edit', 'AnVIL Project Manager Edit Permission'), ('anvil_project_manager_view', 'AnVIL Project Manager View Permission'), ('anvil_project_manager_account_link', 'AnVIL Project Manager Account Link Permission')]},
        ),
    ]
