# Generated by Django 3.2.12 on 2022-11-22 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anvil_consortium_manager', '0008_auto_20221121_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalworkspace',
            name='note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='workspace',
            name='note',
            field=models.TextField(blank=True),
        ),
    ]
