# Generated by Django 3.2.12 on 2022-07-28 22:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('anvil_consortium_manager', '0009_defaultworkspacedata'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AddField(
            model_name='historicalaccount',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
