# Generated by Django 3.2.12 on 2022-09-07 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anvil_consortium_manager', '0010_alter_account_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaluseremailentry',
            name='can_be_verified',
        ),
        migrations.RemoveField(
            model_name='useremailentry',
            name='can_be_verified',
        ),
    ]
