# Generated by Django 3.2.12 on 2022-09-07 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anvil_consortium_manager', '0011_useremailentry_remove_canbeverified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='date_verified',
        ),
        migrations.RemoveField(
            model_name='historicalaccount',
            name='date_verified',
        ),
        migrations.AddField(
            model_name='historicaluseremailentry',
            name='date_verified',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='useremailentry',
            name='date_verified',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
