# Generated by Django 3.2.12 on 2023-04-13 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anvil_consortium_manager', '0011_populate_managed_group_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalmanagedgroup',
            name='email',
            field=models.EmailField(db_index=True, help_text='Email for this group.', max_length=254),
        ),
        migrations.AlterField(
            model_name='managedgroup',
            name='email',
            field=models.EmailField(help_text='Email for this group.', max_length=254, unique=True),
        ),
    ]
