# Generated by Django 3.2.12 on 2023-10-02 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anvil_consortium_manager', '0012_managedgroup_email_unique'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anvilprojectmanageraccess',
            options={'default_permissions': (), 'managed': False, 'permissions': [('anvil_project_manager_edit', 'AnVIL Project Manager Edit Permission'), ('anvil_project_manager_view', 'AnVIL Project Manager View Permission'), ('anvil_project_manager_account_link', 'AnVIL Project Manager Account Link Permission'), ('anvil_project_manager_limited_view', 'AnVIL Project Manager Limited View Permission')]},
        ),
    ]
