# Generated by Django 3.2.12 on 2022-09-08 00:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anvil_consortium_manager', '0012_move_date_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaluseremailentry',
            name='verified_account',
        ),
        migrations.RemoveField(
            model_name='useremailentry',
            name='verified_account',
        ),
        migrations.AddField(
            model_name='account',
            name='verified_email_entry',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='verified_account', to='anvil_consortium_manager.useremailentry'),
        ),
        migrations.AddField(
            model_name='historicalaccount',
            name='verified_email_entry',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='anvil_consortium_manager.useremailentry'),
        ),
    ]
