# Generated by Django 4.2.7 on 2023-11-03 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anvil_consortium_manager', '0013_alter_anvilprojectmanageraccess_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anvilprojectmanageraccess',
            options={'default_permissions': (), 'managed': False, 'permissions': [('anvil_project_manager_staff_edit', 'AnVIL Project Manager Staff Edit Permission'), ('anvil_project_manager_view', 'AnVIL Project Manager View Permission'), ('anvil_project_manager_account_link', 'AnVIL Project Manager Account Link Permission'), ('anvil_project_manager_limited_view', 'AnVIL Project Manager Limited View Permission')]},
        ),
    ]
