# Generated by Django 4.2.7 on 2023-11-06 19:12
# We cannot easily test this migration using django-test-migrations because
# permissions and content types are created via post-migrate signals, and
# django-test-migrations mutes signals.
# So this is only manually tested :(
#
# Some relevant stack overflow posts:
# https://stackoverflow.com/questions/47182012/remove-old-permissions-in-django

from django.db import migrations


def set_up_new_permissions(apps, schema_editor):
    # Map between original codename and updated codename.
    permissions_codename_map = {
        "anvil_project_manager_edit": "anvil_consortium_manager_staff_edit",
        "anvil_project_manager_view": "anvil_consortium_manager_staff_view",
        "anvil_project_manager_limited_view": "anvil_consortium_manager_view",
        "anvil_project_manager_account_link": "anvil_consortium_manager_account_link",
    }
    # Map between original codename and updated name.
    permissions_name_map = {
        "anvil_project_manager_edit": "AnVIL Consortium Manager Staff Edit Permission",
        "anvil_project_manager_view": "AnVIL Consortium Manager Staff View Permission",
        "anvil_project_manager_limited_view": "AnVIL Consortium Manager View Permission",
        "anvil_project_manager_account_link": "AnVIL Consortium Manager Account Link Permission",
    }
    # Rename old permissions if they exist.
    Permission = apps.get_model("auth", "Permission")

    ContentType = apps.get_model("contenttypes", "ContentType")
    try:
        model = ContentType.objects.get(app_label="anvil_consortium_manager", model="anvilprojectmanageraccess")
        for original_codename in permissions_codename_map.keys():
            permission = Permission.objects.get(content_type=model, codename=original_codename)
            print("\nOriginal: ")
            print("  " + permission.codename)
            print("  " + permission.name)
            # Update codename and name.
            permission.codename = permissions_codename_map[original_codename]
            permission.name = permissions_name_map[original_codename]
            print("Updated:")
            print("  " + permission.codename)
            print("  " + permission.name)
            # Save the new permission
            permission.save()
    except ContentType.DoesNotExist:
        # Permissions and ContentTypes are created after all migrations are completed using
        # post-migrate signals. If the ContentType for this app does not exist, then this is
        # the first time that "migrate" has been run, so no permissions need to be renamed.
        pass


# def undo_new_permissions(apps, schema_editor):
#     # Map between original codename and updated codename.
#     permissions_codename_map = {
#         "anvil_project_manager_staff_edit": "anvil_consortium_manager_edit",
#         "anvil_project_manager_staff_view": "anvil_consortium_manager_view",
#         "anvil_project_manager_view": "anvil_consortium_manager_limited_view",
#         "anvil_project_manager_account_link": "anvil_consortium_manager_account_link",
#     }
#     # Map between original codename and updated name.
#     permissions_name_map = {
#         "anvil_project_manager_staff_edit": "AnVIL Project Manager Staff Edit Permission",
#         "anvil_project_manager_staff_view": "AnVIL Project Manager Staff View Permission",
#         "anvil_project_manager_view": "AnVIL Project Manager View Permission",
#         "anvil_project_manager_account_link": "AnVIL Project Manager Account Link Permission",
#     }
#     app_config = apps.get_app_config("anvil_consortium_manager")
#     update_contenttypes(app_config)
#     # Rename old permissions if they exist.
#     Permission = apps.get_model("auth", "Permission")
#     ContentType = apps.get_model("contenttypes", "ContentType")
#     # This raised an Exception:
#     # django.db.utils.OperationalError: no such column: django_content_type.name
#     # Not sure why.
#     model = ContentType.objects.get(app_label="anvil_consortium_manager", model="anvilprojectmanageraccess")
#     for updated_codename in permissions_codename_map.keys():
#         permission = Permission.objects.get(content_type=model, codename=updated_codename)
#         print("\nOriginal: ")
#         print("  " + permission.codename)
#         print("  " + permission.name)
#         # Update codename and name.
#         permission.codename = permissions_codename_map[updated_codename]
#         permission.name = permissions_name_map[updated_codename]
#         print("Updated:")
#         print("  " + permission.codename)
#         print("  " + permission.name)
#         # Don't save yet.
#         permission.save()


class Migration(migrations.Migration):
    dependencies = [
        ("anvil_consortium_manager", "0013_alter_anvilprojectmanageraccess_options"),
    ]

    operations = [
        # I could not get the reverse code to work - see comments above.
        migrations.RunPython(set_up_new_permissions, reverse_code=migrations.RunPython.noop),
    ]
