# Generated by Django 4.2.7 on 2023-11-06 22:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("anvil_consortium_manager", "0014_rename_permissions"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="anvilprojectmanageraccess",
            options={
                "default_permissions": (),
                "managed": False,
                "permissions": [
                    ("anvil_consortium_manager_staff_edit", "AnVIL Consortium Manager Staff Edit Permission"),
                    ("anvil_consortium_manager_staff_view", "AnVIL Consortium Manager Staff View Permission"),
                    ("anvil_consortium_manager_account_link", "AnVIL Consortium Manager Account Link Permission"),
                    ("anvil_consortium_manager_view", "AnVIL Consortium Manager View Permission"),
                ],
            },
        ),
    ]
