# Generated by Django 5.0 on 2024-03-08 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anvil_consortium_manager', '0016_max_length_limits'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalworkspace',
            name='is_requester_pays',
            field=models.BooleanField(default=False, help_text='Indicator of whether the workspace is set to requester pays.'),
        ),
        migrations.AddField(
            model_name='workspace',
            name='is_requester_pays',
            field=models.BooleanField(default=False, help_text='Indicator of whether the workspace is set to requester pays.'),
        ),
    ]
