# Generated by Django 5.0 on 2024-05-30 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anvil_consortium_manager', '0017_workspace_is_requester_pays'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalworkspace',
            name='is_requester_pays',
            field=models.BooleanField(default=False, help_text='Indicator of whether the workspace is set to requester pays.', verbose_name='Requester pays'),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='is_requester_pays',
            field=models.BooleanField(default=False, help_text='Indicator of whether the workspace is set to requester pays.', verbose_name='Requester pays'),
        ),
    ]
