# Generated by Django 5.2 on 2026-02-09 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anvil_consortium_manager', '0019_accountuserarchive'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalworkspace',
            name='app_access',
            field=models.CharField(choices=[('NO_ACCESS', 'No access'), ('LIMITED', 'Limited access'), ('OWNER', 'Owner')], default='OWNER', max_length=20),
        ),
        migrations.AddField(
            model_name='historicalworkspace',
            name='app_access_reason',
            field=models.TextField(blank=True, default='', help_text='Reason why the app is not an owner of this workspace, if applicable.'),
        ),
        migrations.AddField(
            model_name='workspace',
            name='app_access',
            field=models.CharField(choices=[('NO_ACCESS', 'No access'), ('LIMITED', 'Limited access'), ('OWNER', 'Owner')], default='OWNER', max_length=20),
        ),
        migrations.AddField(
            model_name='workspace',
            name='app_access_reason',
            field=models.TextField(blank=True, default='', help_text='Reason why the app is not an owner of this workspace, if applicable.'),
        ),
    ]
