# Generated by Django 5.2 on 2026-02-04 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anvil_consortium_manager', '0019_accountuserarchive'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalworkspace',
            name='is_managed_by_app',
            field=models.BooleanField(default=True, help_text='Indicator of whether this workspace is managed by the app.'),
        ),
        migrations.AddField(
            model_name='workspace',
            name='is_managed_by_app',
            field=models.BooleanField(default=True, help_text='Indicator of whether this workspace is managed by the app.'),
        ),
    ]
