# Generated by Django 5.0 on 2024-05-31 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anvil_consortium_manager', '0020_remove_account_archived_users_account_unlinked_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountuserarchive',
            name='verified_email_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='anvil_consortium_manager.useremailentry'),
        ),
        migrations.AddField(
            model_name='historicalaccountuserarchive',
            name='verified_email_entry',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='anvil_consortium_manager.useremailentry'),
        ),
    ]
