# Generated by Django 5.2 on 2026-02-05 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anvil_consortium_manager', '0020_workspace_is_managed_by_app'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalworkspace',
            name='is_accessible_by_app',
            field=models.BooleanField(default=True, help_text=('Indicator of whether this workspace can be accessed on AnVIL by the app. False indicates deleted workspaces or workspaces where app access has been removed.',)),
        ),
        migrations.AddField(
            model_name='workspace',
            name='is_accessible_by_app',
            field=models.BooleanField(default=True, help_text=('Indicator of whether this workspace can be accessed on AnVIL by the app. False indicates deleted workspaces or workspaces where app access has been removed.',)),
        ),
    ]
