# Generated by Django 5.2 on 2026-02-06 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anvil_consortium_manager', '0021_workspace_is_accessible_by_app'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalworkspace',
            name='reason_inaccessible',
            field=models.TextField(blank=True, default='', help_text='If the workspace is inaccessible by the app, a note about why.'),
        ),
        migrations.AddField(
            model_name='workspace',
            name='reason_inaccessible',
            field=models.TextField(blank=True, default='', help_text='If the workspace is inaccessible by the app, a note about why.'),
        ),
    ]
