# Generated by Django 3.2.12 on 2023-01-04 23:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anvil_consortium_manager', '0004_add_note_field'),
        ('test_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProtectedManagedGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='anvil_consortium_manager.managedgroup')),
            ],
        ),
    ]
