# Generated by Django 3.2.12 on 2023-04-18 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0002_historicaltestworkspacedata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaltestworkspacedata',
            name='study_name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='testworkspacedata',
            name='study_name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
