# Generated by Django 3.2.12 on 2022-08-31 22:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('anvil_consortium_manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExampleWorkspaceData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('study_name', models.CharField(max_length=255)),
                ('consent_code', models.CharField(max_length=16)),
                ('workspace', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='anvil_consortium_manager.workspace')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
