name: ci-tox

# Enable Buildkit and let compose use it to speed up image building
env:
  DOCKER_BUILDKIT: 1
  COMPOSE_DOCKER_CLI_BUILD: 1

on:
  pull_request:
    branches: [ "master", "main" ]
    paths-ignore: [ "docs/**" ]

  push:
    branches: [ "master", "main" ]
    paths-ignore: [ "docs/**" ]


jobs:
  linter:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Code Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
          cache: pip
          cache-dependency-path: |
            requirements/base.txt
            requirements/dev.txt

      - name: Run pre-commit
        uses: pre-commit/action@v2.0.3

  test-sqlite:
    name: "Python ${{ matrix.python-version }} - sqlite"
    runs-on: "ubuntu-latest"
    env:
        BACKEND: sqlite

    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]

    steps:
      - uses: "actions/checkout@v2"
      - uses: "actions/setup-python@v4"
        with:
          python-version: "${{ matrix.python-version }}"
      - name: "Install dependencies"
        run: |
          python -VV
          python -m site
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install --upgrade coverage[toml] virtualenv tox tox-gh-actions

      - name: "Run tox targets for ${{ matrix.python-version }}"
        run: "python -m tox"

      - if: ${{ matrix.python-version == '3.9' }}
        name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

  test-mariadb:
    name: "Python ${{ matrix.python-version }} - mariadb - ${{ matrix.mariadb-version }}"
    runs-on: "ubuntu-latest"
    env:
      DBNAME: test
      DBUSER: root
      DBPASSWORD: rootpw
      DBHOST: 127.0.0.1
      BACKEND: mariadb

    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
        mariadb-version: ["10.3", "10.5"]

    services:
      database:
        image: mariadb:${{ matrix.mariadb-version }}
        env:
          MYSQL_ROOT_PASSWORD: rootpw
          MYSQL_DATABASE: test
        ports:
          - 3306:3306
        options: --tmpfs /var/lib/mysql

    steps:
      - uses: "actions/checkout@v2"
      - uses: "actions/setup-python@v4"
        with:
          python-version: "${{ matrix.python-version }}"
      - name: "Install dependencies"
        run: |
          python -VV
          python -m site
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install --upgrade coverage[toml] virtualenv tox tox-gh-actions

      - name: "Run tox targets for ${{ matrix.python-version }} and mariadb-${{ matrix.mariadb-version }}"
        run: "python -m tox"
